### ISSUE TITLE
访问服务器状态时报错

### ISSUE THREAD

**Issue by ztiandan** [CQUPTMirror/mirror-web-isomorphic#1]
error occured: Error: invalid data
at /Users/danny/Code/GitHub/mirror-web-isomorphic/node_modules/vnstat-dumpdb/vnstat-dumpdb.js:89:15

操作系统mac os 10.11，已经安装过vnstat，通过brew安装的。
@wssgcg1213

**Comment by wssgcg1213** [comment]
vnstat数据库有么

**Comment by ztiandan** [comment]
还真是没有数据库造成的，之前没用过vnstat，现在建立后好了。建议加到配置文档里面，最初在npm install的时候如果没有安装vnstat也会报错

**Comment by wssgcg1213** [comment]
@ztiandan 是的, 在pre install的时候, 会check系统中vnstat的版本和安装状态, 使用的时候需要已经建立vnstat数据库
