### ISSUE TITLE
你好我有个问题。客户端路由renderRouter(routes)传递的参数是否是通过服务端。app.get("/admin");这样传递的

### ISSUE THREAD

**Issue by whevether** [CQUPTMirror/mirror-web-isomorphic#3]
我客户端渲染路由参数是这么写的;
render-routes.js:
import configureStore from 'helpers/configure-store';
import createHistory from 'history/lib/createBrowserHistory';
import React from 'react';
import {render} from 'react-dom';
import {Provider} from 'react-redux';
import {reduxReactRouter, ReduxRouter} from 'redux-router';

export default function renderRoutes (routes) {
  const state = window.__initialState;
  state.router = undefined;
  const store = configureStore(
    reduxReactRouter({createHistory, routes}),
    state
  );

  render(
    <Provider store={store}>
      <ReduxRouter routes={routes} />
    </Provider>,
    document.getElementById('view')
  );
}
//通过页面调用;
import renderRouter from './render-routes';
renderRouter(routes);    

/***********************_服务端**_************************/
route-handle.js:
import configureStore from 'helpers/configure-store';
import {createMemoryHistory} from 'history';
import {match, reduxReactRouter} from 'redux-router/server';

export default function routeHandler (routes, req, res, next) {
  const store = configureStore(reduxReactRouter({
    createHistory: createMemoryHistory,
    routes
  }));
  const url = req.originalUrl;
  store.dispatch(match(url, async (error, redirectLocation, routerState) => {
    if (error) {
      next(error);
    } else if (redirectLocation) {
      res.redirect(302, redirectLocation.pathname + redirectLocation.search);
    } else if (routerState) {
      req.routerState = routerState;
      req.store = store;
      next();
    } else {
      res.status(404).send('Not found');
    }
  }));
}
//服务端页面操作;
import getBaseComponent from 'helpers/get-base-component';
import getDefaultFavicon from 'helpers/default-favicon';
import renderHtml from 'helpers/render-html';
import routeHandler from 'helpers/route-handler';
import routes from 'routers/admin';
import {Router} from 'express';
import {graphql} from 'graphql';
import {getDataDependencies} from 'relate-js';

import schema from '../schema';

const adminRouter = new Router();

// Restrict from here onwards
adminRouter.get('/admin*', (req, res, next) => {
  if (req.isAuthenticated()) {
    res.locals.footer.push({
      tag: 'link',
      props: {
        rel: 'stylesheet',
        type: 'text/css',
        href: 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700'
      }
    });
    res.locals.header.push(getDefaultFavicon(res));

```
if (process.env.NODE_ENV === 'production') {
  res.locals.header.push({
    tag: 'link',
    props: {
      rel: 'stylesheet',
      type: 'text/css',
      href: '/assets/admin.css'
    }
  });
  res.locals.header.push({
    tag: 'link',
    props: {
      rel: 'stylesheet',
      type: 'text/css',
      href: '/assets/common.js.css'
    }
  });
}

res.locals.footer.push({
  tag: 'script',
  props: {
    src: `${res.baseScriptsURL}/assets/admin.js`
  }
});
next();
```

  } else {
    res.redirect('/admin/login');
  }
});

adminRouter.get('/admin*', (req, res, next) => {
  if (req.isAuthenticated()) {
    routeHandler(routes, req, res, next);
  } else {
    next();
  }
});

adminRouter.get('/admin*', async (req, res, next) => {
  if (req.isAuthenticated() && req.routerState) {
    // get component with redux provider and react router
    const component = getBaseComponent(req.store);

```
// get relate js data dependencies
await getDataDependencies(component, async (request) => await graphql(
  schema.getSchema(),
  request.query,
  {
    isAuthenticated: true,
    user: req.user
  },
  request.variables
));

// final render html
res.status(200).send(renderHtml({
  component,
  store: req.store,
  locals: res.locals
}));
```

  } else {
    next();
  }
});

export default adminRouter;

**Comment by wssgcg1213** [comment]
没看懂你这个，我的项目里是用的 react-router。

**Comment by whevether** [comment]
我客户端也是用的react-router .我的意思是客户端路由是不是接收服务端 app.get("/admin",)这个为路由参数或者路劲;

**Comment by wssgcg1213** [comment]
服务端和客户端应该使用同一份路由配置，对于服务端只需要响应正确的 html 就可以了，浏览器端会根据对应路径响应绑定交互事件。

> 客户端路由是不是接收服务端为路由参数或者路劲

这句话没懂

**Comment by wssgcg1213** [comment]
https://github.com/wssgcg1213/koa2-react-isomorphic-boilerplate  
你如果用的这个 repo，你应该去看一下这个
